export enum AnimationName {
  IDLE1 = 'idle1',
  IDLE2 = 'idle2',
  IDLE3 = 'idle3',
  IDLE4 = 'idle4',
  WALK = 'walk',
  JOG = 'jog',
  RUN = 'run',
  SLASH1 = 'slash1',
  SLASH2 = 'slash2',
  SLASH3 = 'slash3',
  SLASH4 = 'slash4',
  SLASH5 = 'slash5',
  ATTACK1 = 'attack1',
  ATTACK2 = 'attack2',
  ATTACK3 = 'attack3',
  ATTACK4 = 'attack4',
}

export enum AnimationIndex {
  IDLE1 = 0,
  IDLE2 = 1,
  IDLE3 = 2,
  IDLE4 = 3,
  WALK = 4,
  JOG = 5,
  RUN = 6,
  SLASH1 = 7,
  SLASH2 = 8,
  SLASH3 = 9,
  SLASH4 = 10,
  SLASH5 = 11,
  ATTACK1 = 12,
  ATTACK2 = 13,
  ATTACK3 = 14,
  ATTACK4 = 15,
}

export const ANIMATION_ORDER = [
  AnimationName.IDLE1,
  AnimationName.IDLE2,
  AnimationName.IDLE3,
  AnimationName.IDLE4,
  AnimationName.WALK,
  AnimationName.JOG,
  AnimationName.RUN,
  AnimationName.SLASH1,
  AnimationName.SLASH2,
  AnimationName.SLASH3,
  AnimationName.SLASH4,
  AnimationName.SLASH5,
  AnimationName.ATTACK1,
  AnimationName.ATTACK2,
  AnimationName.ATTACK3,
  AnimationName.ATTACK4,
]
